/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenderVeiculoRouteImport } from './routes/vender-veiculo'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SegurosRouteImport } from './routes/seguros'
import { Route as FinanciamentoRouteImport } from './routes/financiamento'
import { Route as FichaCadastralRouteImport } from './routes/ficha-cadastral'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VeiculoIdRouteImport } from './routes/veiculo.$id'

const VenderVeiculoRoute = VenderVeiculoRouteImport.update({
  id: '/vender-veiculo',
  path: '/vender-veiculo',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosRoute = SegurosRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamentoRoute = FinanciamentoRouteImport.update({
  id: '/financiamento',
  path: '/financiamento',
  getParentRoute: () => rootRouteImport,
} as any)
const FichaCadastralRoute = FichaCadastralRouteImport.update({
  id: '/ficha-cadastral',
  path: '/ficha-cadastral',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculoIdRoute = VeiculoIdRouteImport.update({
  id: '/veiculo/$id',
  path: '/veiculo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/estoque': typeof EstoqueRoute
  '/ficha-cadastral': typeof FichaCadastralRoute
  '/financiamento': typeof FinanciamentoRoute
  '/seguros': typeof SegurosRoute
  '/sobre': typeof SobreRoute
  '/vender-veiculo': typeof VenderVeiculoRoute
  '/veiculo/$id': typeof VeiculoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/estoque': typeof EstoqueRoute
  '/ficha-cadastral': typeof FichaCadastralRoute
  '/financiamento': typeof FinanciamentoRoute
  '/seguros': typeof SegurosRoute
  '/sobre': typeof SobreRoute
  '/vender-veiculo': typeof VenderVeiculoRoute
  '/veiculo/$id': typeof VeiculoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/estoque': typeof EstoqueRoute
  '/ficha-cadastral': typeof FichaCadastralRoute
  '/financiamento': typeof FinanciamentoRoute
  '/seguros': typeof SegurosRoute
  '/sobre': typeof SobreRoute
  '/vender-veiculo': typeof VenderVeiculoRoute
  '/veiculo/$id': typeof VeiculoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/estoque'
    | '/ficha-cadastral'
    | '/financiamento'
    | '/seguros'
    | '/sobre'
    | '/vender-veiculo'
    | '/veiculo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/estoque'
    | '/ficha-cadastral'
    | '/financiamento'
    | '/seguros'
    | '/sobre'
    | '/vender-veiculo'
    | '/veiculo/$id'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/estoque'
    | '/ficha-cadastral'
    | '/financiamento'
    | '/seguros'
    | '/sobre'
    | '/vender-veiculo'
    | '/veiculo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EstoqueRoute: typeof EstoqueRoute
  FichaCadastralRoute: typeof FichaCadastralRoute
  FinanciamentoRoute: typeof FinanciamentoRoute
  SegurosRoute: typeof SegurosRoute
  SobreRoute: typeof SobreRoute
  VenderVeiculoRoute: typeof VenderVeiculoRoute
  VeiculoIdRoute: typeof VeiculoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vender-veiculo': {
      id: '/vender-veiculo'
      path: '/vender-veiculo'
      fullPath: '/vender-veiculo'
      preLoaderRoute: typeof VenderVeiculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros': {
      id: '/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof SegurosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamento': {
      id: '/financiamento'
      path: '/financiamento'
      fullPath: '/financiamento'
      preLoaderRoute: typeof FinanciamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ficha-cadastral': {
      id: '/ficha-cadastral'
      path: '/ficha-cadastral'
      fullPath: '/ficha-cadastral'
      preLoaderRoute: typeof FichaCadastralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculo/$id': {
      id: '/veiculo/$id'
      path: '/veiculo/$id'
      fullPath: '/veiculo/$id'
      preLoaderRoute: typeof VeiculoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EstoqueRoute: EstoqueRoute,
  FichaCadastralRoute: FichaCadastralRoute,
  FinanciamentoRoute: FinanciamentoRoute,
  SegurosRoute: SegurosRoute,
  SobreRoute: SobreRoute,
  VenderVeiculoRoute: VenderVeiculoRoute,
  VeiculoIdRoute: VeiculoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
